insert into stack.Accounts(parent_id,number,type) values(null,1,1); -- 1
insert into stack.Accounts(parent_id,number,type) values(1,1,2);    -- 2
insert into stack.Accounts(parent_id,number,type) values(1,2,2);    -- 3
insert into stack.Accounts(parent_id,number,type) values(1,3,2);    -- 4
insert into stack.Accounts(parent_id,number,type) values(1,4,2);    -- 5
insert into stack.Accounts(parent_id,number,type) values(2,111,3);  -- 6
insert into stack.Accounts(parent_id,number,type) values(3,122,3);  -- 7
insert into stack.Accounts(parent_id,number,type) values(4,133,3);  -- 8
insert into stack.Accounts(parent_id,number,type) values(5,144,3);  -- 9
insert into stack.Accounts(parent_id,number,type) values(null,2,1); -- 10
insert into stack.Accounts(parent_id,number,type) values(10,1,2);   -- 11
insert into stack.Accounts(parent_id,number,type) values(10,2,2);   -- 12
insert into stack.Accounts(parent_id,number,type) values(10,3,2);   -- 13
insert into stack.Accounts(parent_id,number,type) values(10,4,2);   -- 14
insert into stack.Accounts(parent_id,number,type) values(10,5,2);   -- 15
insert into stack.Accounts(parent_id,number,type) values(10,6,2);   -- 16
insert into stack.Accounts(parent_id,number,type) values(10,7,2);   -- 17
insert into stack.Accounts(parent_id,number,type) values(10,8,2);   -- 18
insert into stack.Accounts(parent_id,number,type) values(11,211,3); -- 19
insert into stack.Accounts(parent_id,number,type) values(12,222,3); -- 20
insert into stack.Accounts(parent_id,number,type) values(13,233,3); -- 21
insert into stack.Accounts(parent_id,number,type) values(14,244,3); -- 22
insert into stack.Accounts(parent_id,number,type) values(15,255,3); -- 23
insert into stack.Accounts(parent_id,number,type) values(16,266,3); -- 24
insert into stack.Accounts(parent_id,number,type) values(17,277,3); -- 25
insert into stack.Accounts(parent_id,number,type) values(18,288,3); -- 26
insert into stack.Accounts(parent_id,number,type) values(null,3,1); -- 27
insert into stack.Accounts(parent_id,number,type) values(27,301,3); -- 28
insert into stack.Accounts(parent_id,number,type) values(null,4,1); -- 29
insert into stack.Accounts(parent_id,number,type) values(29,401,3); -- 30
insert into stack.Accounts(parent_id,number,type) values(30,402,3); -- 31
insert into stack.Accounts(parent_id,number,type) values(null,5,1); -- 32
insert into stack.Accounts(parent_id,number,type) values(32,501,3); -- 33
insert into stack.Accounts(parent_id,number,type) values(32,502,3); -- 34