insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',6,100,1);           -- 1 6,1
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',6,200,1);           -- 2 6,2
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',6,300,1);  -- 3 6,3
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',6,400,1);      -- 4 6,4
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',7,100,1);           -- 5 7,5
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',7,200,1);           -- 6 7,6
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',7,300,1);  -- 7 7,7
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',7,400,1);      -- 8 7,8
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',8,100,1);           -- 9 8,9
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',8,200,1);           -- 10 8,10
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',8,300,1);  -- 11 8,11
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',8,400,1);      -- 12 8,12
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',9,100,1);           -- 13 9,13
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',9,200,1);           -- 14 9,14
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',9,300,1);  -- 15 9,15
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',9,400,1);      -- 16 9,16
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',19,300,2); -- 17 19,17
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',20,300,2); -- 18 20,18
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',21,300,2); -- 19 21,19
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',22,300,2); -- 20 22,20
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',23,300,3); -- 21 23,21
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',24,300,3); -- 22 24,22
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',25,300,3); -- 23 25,23
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',26,300,3); -- 24 26,24
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',28,100,1);          -- 25 28,25
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',28,200,1);          -- 26 28,26
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',28,300,1); -- 27 28,27
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',28,400,1);     -- 28 28,28
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',30,100,1);          -- 29 30,29
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',30,200,1);          -- 30 30,30
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',30,300,1); -- 31 30,31
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',30,400,1);     -- 32 30,32
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',31,100,1);          -- 33 31,33
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',31,200,1);          -- 34 31,34
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',31,300,1); -- 35 31,35
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',31,400,1);     -- 36 31,36
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',33,100,1);          -- 37 33,37
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',33,200,1);          -- 38 33,38
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',33,300,1); -- 39 33,39
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',33,400,1);     -- 40 33,40
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',34,100,1);          -- 41 34,41
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на воду',34,200,1);          -- 42 34,42
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на электричество',34,300,1); -- 43 34,43
insert into stack.Counters (name,acc_id,service,tarif) values ('Счетчик на отопление',34,400,1);     -- 44 34,44